### PR TITLE
Add rebuildFromPlayactions to the game endpoint

### PR DESCRIPTION
**Pull request by ScottTrenda**
Adds a `rebuildFromPlayActions` method to the ngin client Game controller.

### CODE REVIEW

**Comment by sportngin-code-climate** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/52403ace89af7e683c02b17d/compare/TOURNEY-1729">analyzed this pull request</a>.

**Comment by jessehouchins** [comment]
CR :+1:

**Comment by ScottTrenda** [comment]
QA :+1: from within sport admin

**Comment by mikefrey** [comment]
Published ngin_client@0.2.60

**Pull request merged**
